### ISSUE TITLE
Create a TVoS target ( enhancement )

### ISSUE THREAD

**Issue by orff** [yoshisuga/MAME4iOS#1] opened 2016-05-23 02:52 UTC
I think this project is further along than some of the other meme EMUs, but it needs a TVoS target

**Comment by yoshisuga** [comment] 2016-05-23 18:25
I've created a tvOS branch and am planning to support tvOS, eventually.

**Comment by Keinoom** [comment] 2016-08-28 19:18
Any progress in tvOS app ? MameAppleTV is so old (0.37b5) :( We need your version of Mame (0.139) ;)

**Comment by JonnyBoy333** [comment] 2016-09-07 04:26
Second this. MameAppleTV has many bugs and doesn't support multiple controllers. Would be fantastic to play mame games natively on the big screen in all their glory.

**Comment by yoshisuga** [comment] 2016-09-07 17:09
I'm starting to look at this again. I've taken the first steps by creating a tvOS target, and I got the MAME library to build for AppleTV's arm64 architecture.

**Comment by yoshisuga** [comment] 2016-09-07 23:56
Oops I take that back - I wasn't able to get the MAME library to compile for arm64. There are some issues relating to casting to 32-bit ints, and I wasn't able to quickly fix it. If anyone can checkout the tvos-arm64 branch and try to get the mame library to compile, it'd be rather trivial to get this working under tvOS.

**Comment by romadu** [comment] 2016-09-09 09:56
Hi
I've use (int)(size_t) to fix most of the errors when making libmamearm64, but am unsure how to post the modified files. 

I'm not sure how to resolve the errors in /src/emu/emualloc.c. Perhaps resolving the FPTR casting errors will fix most of the make errors in libmamearm64, without needing to modify all the files using FPTR.

src/emu/emualloc.c:236:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(item.m_ptr) % k_hash_prime;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/emu/emualloc.c:267:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(ptr) % k_hash_prime;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/emu/emualloc.c:306:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(ptr) % k_hash_prime;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/emu/emualloc.c:439:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(base) % k_hash_prime;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/emu/emualloc.c:464:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(ptr) % k_hash_prime;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/emu/emualloc.c:484:16: error: cast from pointer to smaller type 'FPTR'
      (aka 'unsigned int') loses information
        int hashval = reinterpret_cast<FPTR>(entry->m_base) % k_hash_prime;

**Comment by yoshisuga** [comment] 2016-09-09 17:52
Hi @romadu - I don't see the pull request - do you have a link to it?

I think I figured out the issue - I just had to do `PTR64=1` for the arm64 target in the makefile - which I'm guessing is what you did :) Thanks for the FPTR hint - i found where that was defined and then found the PTR64 compiler flag and I was like ah!

It's in the process of compiling right now so hopefully that was it. Thanks again!

**Comment by romadu** [comment] 2016-09-10 03:50
That's great that you managed to fix it. Let me know if you still want my pull request - it sounds like you might not need it now anyway

**Comment by JonnyBoy333** [comment] 2016-09-25 00:25
Hey, any news with the TVos version? I'd love to be a beta tester :).

**Comment by Keinoom** [comment] 2016-09-25 08:24
Me too ;)

**Comment by yoshisuga** [comment] 2016-09-26 23:08
I've ran into a roadblock and I haven't had time to figure out a way around it. The MAMI library requires the libstdc++ library to be linked but it's been removed from tvOS, and I can't just go in and fix references to string functions I know nothing about.

If anyone knows a way around this, please let me know.

**Comment by romadu** [comment] 2016-09-27 01:27
This project has a working instance of Mame on tvos. I wonder if it
provides any clues about how to link libstdc++.

https://github.com/kevsmithpublic/MameAppleTV

**Comment by JonnyBoy333** [comment] 2016-09-27 01:36
That project is based on an older MAME core and probably isn't very relatable to this project. In any case it looks like libstdc++ has been deprecated in favor of the newer libc++ standard. Apple stopped supporting libstdc++ in ios 9.2 and forced everyone to upgrade their apps. Now if you asked me how to upgrade them, I would have no idea ;).

**Comment by romadu** [comment] 2016-09-27 01:45
This discussion implies that this could be a difficult problem to solve

http://stackoverflow.com/questions/12542971/using-libstdc-compiled-libraries-with-clang-stdlib-libc

**Comment by DarrenBranford** [comment] 2016-11-07 17:52
While this is not my main personal priority, I would love to be able to look into this as 64bit support for mobile devices that support it would be great, too. However, I am having issues building libmamearm64. Taking cues from the various branches, I am able to compile libmamearm64, but building MAME4IOS with an arm64 architecture always produces an error..

`ld: warning: ignoring file /Volumes/Toshiba/Projects/MAME4iOS/xcode/MAME4iOS/libmamearm64.a, file was built for archive which is not the architecture being linked (arm64): /Volumes/Toshiba/Projects/MAME4iOS/xcode/MAME4iOS/libmamearm64.a`

Has anyone else verified that their libmamearm64 is actually working?

**Comment by yoshisuga** [comment] 2016-11-12 19:33
Hi @DarrenBranford !

I went down the same path as you did, and I think you get that if you built the MAME library using the iPhoneOS SDK, not the tvOS sdk.

IIRC, if you build using the tvOS SDK (I think you specify this in the makefile by overriding a path), you can create the library, but the problem is that libstdc++ isn't supported in tvOS.

My guess is the solution is to support libc++, but that'd mean making code changes to the MAME library, or doing some kind of compiler trickery to make it work. I know someone with more C++ experience can probably figure this out but its beyond me at the moment.

**Comment by yoshisuga** [comment] 2018-09-26 00:33
I updated MAME4iOS to build in Xcode 10. Part of the process involved building using libc++ since libstdc++ is gone in Xcode 10. 

I was able to build using libc++ so that means a tvOS port is now in the realm of possibilities! I'll be looking into this later.

**Comment by yoshisuga** [comment] 2019-01-13 22:58
An update on tvOS: I spent a weekend trying to get MAME to run on tvOS, and I'm happy to announce getting MAME4iOS running and playing games on AppleTV!

It's still early as I just wanted to first get the thing to run so I stripped out the Settings, netplay and other extraneous things to get the main functionality to work. It currently only works with the following limitations:

- only works with an mfi controller (tv remote to be added soon)
- mfi controller needs to be connected before running
- hitting the menu button on the remote will not exit; try using the "tv" button on the remote instead
- unable to reach the menu to load/save state/change settings (will be added later)
- may crash on resume

If you want to try it out, you need to checkout the `tvos` branch and build the mame library for tvos by doing:

`make tvOS=1`
`mv libmamearm64.a libmamearm64-tvos.a`

In Xcode, choose the MAME tvOS target, and build and run on the AppleTV.

I'll merge the tvOS branch into master after adding some bare necessities for AppleTV, and I might have broke some of the UI on the iPhone/iPad side because of some refactoring I had to do.

**Comment by yoshisuga** [comment] 2019-01-16 07:41
tvOS support is now in the master branch! There's still work that needs to be done (adding Settings, Siri Remote support) but the core functionality is there, and it plays games!

Closing!

**Closed by yoshisuga** 2019-01-16 07:41 UTC
